# Generated by Django 4.1.6 on 2023-02-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='close_only',
            field=models.BooleanField(default=False),
        ),
    ]
