# Generated by Django 4.1.6 on 2023-02-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_close_only'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
