# Generated by Django 4.1.6 on 2023-02-16 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccount_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCloseFriendRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friended', to=settings.AUTH_USER_MODEL)),
                ('friender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
