# Generated by Django 4.1.6 on 2023-02-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userclosefriendrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bio',
            field=models.TextField(blank=True, default='Your bio here'),
        ),
    ]
