# Generated by Django 4.1.6 on 2023-02-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useraccount_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
